---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator/

images:
  - name: kubernetes-reflector
    newName: emberstack/kubernetes-reflector
    newTag: "6.1.47"

...
