---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: kubernetes-reflector

rules:
  - apiGroups:
      - ""
    resources:
      - "configmaps"
      - "secrets"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "namespaces"
    verbs:
      - "watch"
      - "list"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "watch"
      - "list"
  - apiGroups:
      - "certmanager.k8s.io"
    resources:
      - "certificates"
      - "certificates/finalizers"
    verbs:
      - "watch"
      - "list"
  - apiGroups:
      - "cert-manager.io"
    resources:
      - "certificates"
      - "certificates/finalizers"
    verbs:
      - "watch"
      - "list"

...
