---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubernetes-reflector

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: kubernetes-reflector

      securityContext:
        fsGroup: 2000

      containers:
        - name: server
          image: kubernetes-reflector
          imagePullPolicy: IfNotPresent

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000

          env:
            - name: ES_Serilog__MinimumLevel__Default
              value: "Information"

          ports:
            - name: http
              containerPort: 25080
              protocol: TCP

          resources:
            requests:
              cpu: "0.1"
              memory: "64Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

          readinessProbe:
            httpGet:
              path: /healthz
              port: http

...
