---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: kubernetes-reflector
  labels:
    app.kubernetes.io/name: kubernetes-reflector
    app.kubernetes.io/component: operator

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-reflector
      app.kubernetes.io/component: operator

  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-reflector
        app.kubernetes.io/component: operator

    spec:
      enableServiceLinks: false
      serviceAccountName: kubernetes-reflector

      securityContext:
        fsGroup: 2000

      containers:
        - name: server
          image: kubernetes-reflector
          imagePullPolicy: IfNotPresent

          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000

          envFrom:
            - configMapRef:
                name: kubernetes-reflector

          ports:
            - name: http
              containerPort: 25080
              protocol: TCP

          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

          readinessProbe:
            httpGet:
              path: /healthz
              port: http

...
