---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml

configMapGenerator:
  - name: kubernetes-reflector
    options:
      labels:
        app.kubernetes.io/name: kubernetes-reflector
        app.kubernetes.io/component: operator
    literals:
      - ES_Serilog__MinimumLevel__Default=Information

images:
  - name: kubernetes-reflector
    newName: emberstack/kubernetes-reflector
    newTag: "9.1.17"

...
